### ISSUE TITLE
Testing setup

### ISSUE THREAD

**Issue by cbrnr** [Yida-Lin/SigVisualizer#3]
I'd like to test the app by receiving some artificial LSL streams - do you know if there is a simple LSL outlet I could use? Ideally, this outlet would produce sinusoidal, rectangular, and sawtooth signals instead of random noise.

**Comment by cbrnr** [comment]
To answer my question: I think we can easily do this with these examples: https://github.com/sccn/labstreaminglayer/tree/master/LSL/liblsl-Python/examples

Also, I think we don't need to include `pylsl.py` in this project since we can `pip install pylsl`.

**Comment by cbrnr** [comment]
Hm, unfortunately this doesn't seem to work. Once I click on the "Update streams" button, the app crashes:

```
Traceback (most recent call last):
  File "/Users/clemens/Repositories/SigVisualizer/paintwidget.py", line 43, in run
    chunk, timestamps = self.inlet.pull_chunk(max_samples=self.chunkSize)
  File "/Users/clemens/anaconda/lib/python3.6/site-packages/pylsl/pylsl.py", line 844, in pull_chunk
    handle_error(errcode)
  File "/Users/clemens/anaconda/lib/python3.6/site-packages/pylsl/pylsl.py", line 1134, in handle_error
    raise InternalError("an internal error has occurred.")
pylsl.pylsl.InternalError: an internal error has occurred.
```

**Comment by Yida-Lin** [comment]
@cbrnr Hi Clemens! Yes I also have another command line application called 'XDF player', which can be used for testing the SigVisualizer. I am currently working on adding a GUI for it though, may take a few days.

Yes the sivualizer is currently quite fragile; I will work on it more and let you know when it is more mature!

Thanks

**Comment by cbrnr** [comment]
I'd like to make some cosmetic changes to the code to make it more Pythonic. I could do this today, so maybe you can hold off new changes to make merging easier?

No need to spend time on a GUI for the signal generator, a simple command line tool is sufficient. The simple [send data example](https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl-Python/examples/SendData.py) should be working at some point, right?

**Comment by Yida-Lin** [comment]
Yes that would be great, thanks Clemens!

I am going to bed now so please feel free to modify it however you'd like :)

Yes maybe a GUI for sending example is unnecessary... the send data example you mentioned is sufficient (I will share my 'XDF player' on a separate repo soon also)
